### ISSUE TITLE
question about use-case of ct/pt from sample code

### ISSUE THREAD

**Issue by citypw** [handshake-org/goosig#8]
Hi,

Hiding the each party's real pubkey is a very important feature for a decentralized platform. I took a glance at the sample code. In the scenario of the multi-party are using handshake-based RSA, each party will generate their own pub/priv key pair and generate an random number s_prime based on pubkey. Then generate C1 based on s_prime. IIRC, C1 is the only info being published which related w/ the pubkey and everyone can access to. There's one thing I still don't figure: 

// Encrypt s_prime to user's pubkey.
const ct = goo.encrypt(s_prime, pub);

// User decrypts the encrypted payload.
const pt = goo.decrypt(ct, priv);

If A only can access B's C1, how does A get B's pubkey and use it to encrypt s_prime? Or what use-case would that be?

**Comment by chjj** [comment]
So, there's actually 3 parties involved here: the challenger, the signer, and the verifier. The challenger has access to the signer's RSA public key, but they want to ensure that the verifier does not. This is a problem because the verifier obviously needs something to verify the signature against.

The challenger generate a random scalar `s` which is used to commit to the modulus `n` of the signer's regular RSA pubkey (`(g^n * h^s) mod m` where `m` is a public RSA modulus with an unknown factorization). That commitment is `C1` and is published publicly so the verifier has access to it. The trick here is that `C1` does not reveal `n`. The challenger then encrypts this scalar and "sends" it to the signer ("send" may not be the right word, see below).

This scheme assumes that the signer trusts the challenger to retain the privacy of their RSA modulus. 

The main benefit here is that this scheme is non-interactive and requires no back-and-forth between the challenger and signer. The challenger can generate this encrypted scalar and post it somewhere for the signer to find later.

**Comment by citypw** [comment]
This does make more sense. Thanks for the explanation.
